Catch exception when EventSender stopped
spring-projects/spring-amqp pull request #1248
Opened 2020-09-02 12:04 UTC by Z-Beatles

`org.springframework.amqp.rabbit.logback.AmqpAppender.java`
```java
protected class EventSender implements Runnable {
	@Override
	public void run() {
		try {
			RabbitTemplate rabbitTemplate = new RabbitTemplate(AmqpAppender.this.connectionFactory)
			while (true) {
				final Event event = AmqpAppender.this.events.take();

				MessageProperties amqpProps = prepareMessageProperties(event);

				String routingKey = AmqpAppender.this.routingKeyLayout.doLayout(event.getEvent());

				sendOneEncoderPatternMessage(rabbitTemplate, routingKey);

				doSend(rabbitTemplate, event, event.getEvent(), name, amqpProps, routingKey);
			}
		}
		catch (InterruptedException e) {
			Thread.currentThread().interrupt();
		}
	}
}
...
```
Any exceptions in this `while(true){}` code block will be lost (except `InterruptedException`).

For example, when sending a message using a custom LoggingLayout to encodeMessage, any exceptions thrown from `doLayout()` will not be caught. The sending thread will stop and we have no way of knowing what went wrong.

2020-09-02 12:04 UTC, pivotal-issuemaster commented
@Z-Beatles Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1248)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1248) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-09-02 12:06 UTC, pivotal-issuemaster commented
@Z-Beatles Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1248)!

2020-09-08 16:25 UTC, artembilan requested changes
Any chances to have some test-case on the matter?
Thanks

2020-09-16 12:25 UTC, Z-Beatles commented
I have tried to provide a test-case but it affects other test-case. The problem is as I described, EventSender-thread missing catch exception. Hope to get help.

2020-09-16 13:05 UTC, artembilan approved these changes
I'm OK with the fix then since we need to release today.

@garyrussell , WDYT?

2020-09-16 13:36 UTC, merged