GH-1422: @RabbitListener: Fix Broker-Named Queues
spring-projects/spring-amqp pull request #1423
Opened 2022-02-10 22:32 UTC by garyrussell

Resolves https://github.com/spring-projects/spring-amqp/issues/1422

Broker-named queues did not work with `@RabbitListener` because the BPP
only passed the name of the queue bean, not the bean itself, into the
endpoint.

Support bean injection; fall back to the previous behavior if a mixture
of beans and names are encountered (the containers don't support both
types of configuration).

Add a note to the javadoc to indicate that broker-named queues are not
supported via `queuesToDeclare` and `bindings` properties; such queues
must be declared as discrete beans.

2022-02-10 23:26 UTC, garyrussell commented
Forgot to indicate **cherry-pick to 2.4.x, 2.3.x**

2022-02-11 14:12 UTC, artembilan requested changes
I see a restriction logic here in the `AbstractRabbitListenerEndpoint`:
```
if (queuesEmpty) {
				Collection<String> names = qNames;
				container.setQueueNames(names.toArray(new String[0]));
			}
			else {
				Collection<Queue> instances = getQueues();
				container.setQueues(instances.toArray(new Queue[0]));
			}
```

But at the same time I see that listener container has also this contract:
```
	/**
	 * Add queue(s) to this container's list of queues.
	 * @param queueNames The queue(s) to add.
	 */
	public void addQueueNames(String... queueNames) {
		Assert.notNull(queueNames, "'queueNames' cannot be null");
		Assert.noNullElements(queueNames, "'queueNames' cannot contain null elements");
		addQueues(Arrays.stream(queueNames)
				.map(Queue::new)
				.toArray(Queue[]::new));
	}

	/**
	 * Add queue(s) to this container's list of queues.
	 * @param queues The queue(s) to add.
	 */
	public void addQueues(Queue... queues) {
		Assert.notNull(queues, "'queues' cannot be null");
		Assert.noNullElements(queues, "'queues' cannot contain null elements");
		if (isRunning()) {
			for (Queue queue : queues) {
				Assert.hasText(queue.getName(), "Cannot add broker-named queues dynamically");
			}
		}
		this.queues.addAll(Arrays.asList(queues));
	}
```
Doesn't that mean that we can change `AbstractRabbitListenerEndpoint` and have mixed configuration with those annotations?

Thanks

2022-02-14 14:50 UTC, garyrussell commented
We could do that, but it would break a lot of tests; since this is a bit of a corner case, I wanted to make only minimal changes to support it. I doubt that someone will define a listener that listens to a broker-named queue as well as others. We can always revisit in future.

2022-02-14 16:40 UTC, garyrussell commented
I wasn't planning on doing so (aside from the comments I added to the javadocs); it's a bug. What do you recommend?

2022-02-14 16:43 UTC, garyrussell commented
https://docs.spring.io/spring-amqp/docs/current/reference/html/#containers-and-broker-named-queues

2022-02-14 16:47 UTC, garyrussell commented
Good point; will push a commit.

2022-02-14 17:13 UTC, merged

2022-02-14 17:17 UTC, artembilan commented
... and cherry-picked to `2.4.x` & `2.3.x`