AsyncMessageProcessingConsumer countdown when the container is not active
spring-projects/spring-amqp pull request #1488
Opened 2022-08-03 14:06 UTC by renyansongno1

Resolves https://github.com/spring-projects/spring-amqp/issues/1487

2022-08-03 14:06 UTC, pivotal-cla commented
@renyansongno1 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1488)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1488) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-08-03 14:08 UTC, pivotal-cla commented
@renyansongno1 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp&pullRequestId=1488)!

2022-08-03 18:06 UTC, artembilan approved these changes
LGTM, but is there a chance to add some unit test to confirm the problem and the fix?

Thanks

2022-08-09 07:06 UTC, renyansongno1 commented
@artembilan Hi, I have submitted the test code, please review.

2022-08-09 14:40 UTC, artembilan requested changes

2022-08-09 14:40 UTC, artembilan commented on spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/SimpleMessageListenerContainerTests.java
> +	private class TestExecutor extends SimpleAsyncTaskExecutor {
```suggestion
	private static final class TestExecutor extends SimpleAsyncTaskExecutor {
```

Also, please, add your name to the `@author` list of affected classes.

2022-08-10 02:23 UTC, renyansongno1 commented
@artembilan Thank you for your time!

2022-08-10 14:40 UTC, merged

2022-08-10 15:14 UTC, artembilan commented
... and cherry-picked to `2.4.x`

@renyansongno1 ,

thank you very much for the contribution; looking forward for more!