Make use compareAndSet instead lock
spring-projects/spring-amqp pull request #2862
Opened 2024-10-18 14:58 UTC by laststem

### Changes
1. Use compareAndSwap operation: CAS operation is more efficient than lock + unlock operation.
2. Set the parameters((superStreamRouting, producerCustomizer, ...) required to create a producer in advance : The parameters used to create a producer have no effect after the producer has been created, so i changed them to only have an effect when the producer is not initialized.
3. Rename streamConverter to streamMessageConverter.

### New found
- If send() and close() are executed at the same time, there is a race condition where producer becomes null but trying to call a method on producer

2024-10-18 15:07 UTC, artembilan requested changes

2024-10-18 15:17 UTC, laststem commented on spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamTemplate.java
> +		return this.producer;
You're right. my mistake.

2024-10-18 18:17 UTC, artembilan commented
I think we need to revert all your changes, and just add extra `if (this.producer == null) {` before calling `lock()`.
This way only first calls to the `createOrGetProducer()` would suffer from `Lock` delay.

2024-10-19 13:37 UTC, ngocnhan-tran1996 commented
@laststem 

As @artembilan said 
I have a PR #2874 for adding condition `this.producer`. You can check out and continue to contributing your idea

2024-10-19 15:31 UTC, artembilan commented
Well, I even would say that this is a duplicate of that https://github.com/spring-projects/spring-amqp/pull/2874. So, closed respectively .
@laststem , feel free to come back to us with any other contribution. Thank you for your effort!

2024-10-19 15:31 UTC, closed without merging