Improve condition
spring-projects/spring-amqp pull request #2874
Opened 2024-10-19 10:01 UTC by ngocnhan-tran1996

This PR includes:
- Check `this.producer` before calling `lock()` to `createOrGetProducer()` and `close` method
- Modernize `switch` pattern

2024-10-19 13:28 UTC, artembilan commented
@ngocnhan-tran1996 , 
Thank you for contribution!
Looks like you are addressing the other PR : https://github.com/spring-projects/spring-amqp/pull/2862. Can yo mention that then and other contributor know, so we all don’t spend time looking into duplication?

2024-10-20 15:02 UTC, artembilan requested changes

2024-10-21 15:25 UTC, artembilan approved these changes
Pulling locally for final review and merge...

2024-10-21 16:02 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-amqp/commit/33da2a6158a49ff62a37cbebc5ac1e8ac5e73839.

@ngocnhan-tran1996 ,

thank you for contribution; looking forward for more!

A couple remarks:

Why your fork is called `spring-amqp-fork`? Why it cannot be just `spring-amqp` in your repositories?
Please, make yourself familiar with this article to understand of the commit message importance: https://cbea.ms/git-commit/.
Plus, GitHub is able to turn the first commit of the PR to its description.
This way we can save some time for extra typing.

2024-10-21 16:02 UTC, closed without merging

2024-10-21 16:40 UTC, artembilan commented
This PR has also fixed https://github.com/spring-projects/spring-amqp/issues/2861.

2024-10-21 16:46 UTC, ngocnhan-tran1996 commented
Thanks @artembilan

I have a private repository name `spring-amqp` for some examples related `spring-amqp`. So I will rename it.

2024-10-21 21:48 UTC, artembilan commented on spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/producer/RabbitStreamTemplate.java
> +		if (this.producer == null) {
Done: https://github.com/spring-projects/spring-amqp/commit/f150bf531ae9cf0f8ae7e278889e7f9b084ffee6